#!/bin/sh
if [ `wget -O - -q http://127.0.0.1/web/deviceinfo | grep "\(<\|</\)e2distroversion" | tr -d '\n' | sed "s/.*<e2distroversion>\(.*\)<\/e2distroversion>.*/\\1\n/"` = 'teamblue' ]; then
	echo "The Skin PlatoonHD has been activated successfully."
else
	echo "No supported Image found."
	echo "The Skin PlatoonHD is specified for 'teamBlue' Image."
    wget -q -O /dev/null "http://127.0.0.1/web/message?type=1&text=No%20supported%20Image%20found.%0AThe%20Skin%20PlatoonHD%20is%20specified%20for%20'teamBlue'%20Image.&timeout=13" || true
fi
if [ -f /tmp/platoonhd-skin.xml ]; then
    mv -f /tmp/platoonhd-skin.xml /usr/share/enigma2/PlatoonHD/skin.xml
else
    cp /usr/share/enigma2/PlatoonHD/act-skin.xml /usr/share/enigma2/PlatoonHD/skin.xml
fi
if [ -d /tmp/platoonhd-graphics ]; then
    mv -f /tmp/platoonhd-graphics/* /usr/share/enigma2/PlatoonHD/graphics/
fi
