#!/bin/sh
echo "                                                           "
echo "       PlatoonHD Skin successful removed.                 "
echo "                                                           "
