#!/bin/sh
echo "                                                           "
echo "       The Skin PlatoonHD is now being installed...       "
echo "                                                           "
