#!/bin/sh
if [ -f /usr/lib/enigma2/python/Components/Converter/PlatoonHDClockToText.pyc ]; then
    rm /usr/lib/enigma2/python/Components/Converter/PlatoonHDClockToText.pyc
fi
if [ -f /usr/lib/enigma2/python/Components/Converter/PlatoonHDDiskSpace.pyc ]; then
    rm /usr/lib/enigma2/python/Components/Converter/PlatoonHDDiskSpace.pyc
fi
if [ -f /usr/lib/enigma2/python/Components/Converter/PlatoonHDDolbyState.pyc ]; then
    rm /usr/lib/enigma2/python/Components/Converter/PlatoonHDDolbyState.pyc
fi
if [ -f /usr/lib/enigma2/python/Components/Converter/PlatoonHDECMLine.pyc ]; then
    rm /usr/lib/enigma2/python/Components/Converter/PlatoonHDECMLine.pyc
fi
if [ -f /usr/lib/enigma2/python/Components/Converter/PlatoonHDEventName.pyc ]; then
    rm /usr/lib/enigma2/python/Components/Converter/PlatoonHDEventName.pyc
fi
if [ -f /usr/lib/enigma2/python/Components/Converter/PlatoonHDEventTime.pyc ]; then
    rm /usr/lib/enigma2/python/Components/Converter/PlatoonHDEventTime.pyc
fi
if [ -f /usr/lib/enigma2/python/Components/Converter/PlatoonHDMenuIconPath.pyc ]; then
    rm /usr/lib/enigma2/python/Components/Converter/PlatoonHDMenuIconPath.pyc
fi
if [ -f /usr/lib/enigma2/python/Components/Converter/PlatoonHDMovieReference.pyc ]; then
    rm /usr/lib/enigma2/python/Components/Converter/PlatoonHDMovieReference.pyc
fi
if [ -f /usr/lib/enigma2/python/Components/Converter/PlatoonHDRemainingToText.pyc ]; then
    rm /usr/lib/enigma2/python/Components/Converter/PlatoonHDRemainingToText.pyc
fi
if [ -f /usr/lib/enigma2/python/Components/Converter/PlatoonHDServiceEndTime.pyc ]; then
    rm /usr/lib/enigma2/python/Components/Converter/PlatoonHDServiceEndTime.pyc
fi
if [ -f /usr/lib/enigma2/python/Components/Converter/PlatoonHDServiceInfoEX.pyc ]; then
    rm /usr/lib/enigma2/python/Components/Converter/PlatoonHDServiceInfoEX.pyc
fi
if [ -f /usr/lib/enigma2/python/Components/Converter/PlatoonHDServiceName2.pyc ]; then
    rm /usr/lib/enigma2/python/Components/Converter/PlatoonHDServiceName2.pyc
fi
if [ -f /usr/lib/enigma2/python/Components/Renderer/PlatoonHDDolbyIcon.pyc ]; then
    rm /usr/lib/enigma2/python/Components/Renderer/PlatoonHDDolbyIcon.pyc
fi
if [ -f /usr/lib/enigma2/python/Components/Renderer/PlatoonHDEmptyEpg.pyc ]; then
    rm /usr/lib/enigma2/python/Components/Renderer/PlatoonHDEmptyEpg.pyc
fi
if [ -f /usr/lib/enigma2/python/Components/Renderer/PlatoonHDEmptyEpg3.pyc ]; then
    rm /usr/lib/enigma2/python/Components/Renderer/PlatoonHDEmptyEpg3.pyc
fi
if [ -f /usr/lib/enigma2/python/Components/Renderer/PlatoonHDPixmapScaler.pyc ]; then
    rm /usr/lib/enigma2/python/Components/Renderer/PlatoonHDPixmapScaler.pyc
fi
if [ -f /usr/lib/enigma2/python/Components/Renderer/PlatoonHDRunningText.pyc ]; then
    rm /usr/lib/enigma2/python/Components/Renderer/PlatoonHDRunningText.pyc
fi
if [ -f /usr/lib/enigma2/python/Components/Renderer/PlatoonHDServiceIcon.pyc ]; then
    rm /usr/lib/enigma2/python/Components/Renderer/PlatoonHDServiceIcon.pyc
fi
if [ -f /usr/lib/enigma2/python/Components/Renderer/PlatoonHDSingleEpgList.pyc ]; then
    rm /usr/lib/enigma2/python/Components/Renderer/PlatoonHDSingleEpgList.pyc
fi
if [ -f /usr/lib/enigma2/python/Components/Renderer/PlatoonHDVolumeText.pyc ]; then
    rm /usr/lib/enigma2/python/Components/Renderer/PlatoonHDVolumeText.pyc
fi
if [ -f /usr/lib/enigma2/python/Plugins/Extensions/PlatoonHD/__init__.pyc ]; then
    rm /usr/lib/enigma2/python/Plugins/Extensions/PlatoonHD/__init__.pyc
fi
if [ -f /usr/lib/enigma2/python/Plugins/Extensions/PlatoonHD/PlatoonHD.pyc ]; then
    rm /usr/lib/enigma2/python/Plugins/Extensions/PlatoonHD/PlatoonHD.pyc
fi
if [ -f /usr/lib/enigma2/python/Plugins/Extensions/PlatoonHD/ping.pyc ]; then
    rm /usr/lib/enigma2/python/Plugins/Extensions/PlatoonHD/ping.pyc
fi
if [ -f /usr/lib/enigma2/python/Plugins/Extensions/PlatoonHD/plugin.pyc ]; then
    rm /usr/lib/enigma2/python/Plugins/Extensions/PlatoonHD/plugin.pyc
fi
if [ -f /usr/share/enigma2/PlatoonHD/skin.xml ]; then
    cp -f /usr/share/enigma2/PlatoonHD/skin.xml /tmp/platoonhd-skin.xml
fi
if [ -d /tmp/platoonhd-graphics ]; then
    cp -f /usr/share/enigma2/PlatoonHD/graphics/* /tmp/platoonhd-graphics/
else
    mkdir /tmp/platoonhd-graphics
    cp /usr/share/enigma2/PlatoonHD/graphics/* /tmp/platoonhd-graphics/
fi
if [ -d /usr/share/enigma2/PlatoonHD ]; then
    rm -r /usr/share/enigma2/PlatoonHD
fi
